project:
  type: website

website:
  title: "Nutchanok Saitin - Portfolio"
  navbar:
    right:
      - text: "Home"
        file: projects.qmd
      - text: "About Me"
        file: about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/nutchanok-saitin-9022a6189
      - icon: github
        href: https://github.com/NutchanokS

format:
  html:
    theme: yeti
    css: styles.css



